import * as path from 'path';
import * as fs from 'fs';
import { v4 as uuidv4 } from 'uuid';
import {
  VideoGenerationResult,
  WorkflowState,
  Platform,
  BackgroundMood,
} from '../types';
import { OpenAIService } from '../services/openai.service';
import { KieLipSyncService } from '../services/kie-lipsync.service';
import { FFmpegService } from '../services/ffmpeg.service';
import { ElevenLabsService } from '../services/elevenlabs.service';
import { CaptionsService, YOUTUBE_SHORTS_STYLE } from '../services/captions.service';
import { GCSStorageService } from '../services/gcs-storage.service';
import { LipSyncScene } from './grok-lipsync.workflow';

/**
 * Scene generated by OpenAI for lip sync
 */
interface GeneratedScene {
  id: string;
  dialogue: string;
  visual: string;
  title: string;
}

/**
 * Grok Lip Sync Auto Workflow
 *
 * Fully automatic video generation using Grok's native lip sync.
 * Flow:
 * 1. User provides topic + niche + background mood
 * 2. OpenAI generates script with scenes (dialogue + visuals)
 * 3. KIE.AI generates lip-synced video segments
 * 4. FFmpeg concatenates with frame chaining
 *
 * No ElevenLabs needed - Grok handles voice + lip sync natively!
 */
export class GrokLipSyncAutoWorkflow {
  private openai: OpenAIService;
  private kieLipSync: KieLipSyncService;
  private ffmpeg: FFmpegService;
  private elevenlabs?: ElevenLabsService;
  private captions: CaptionsService;
  private gcsStorage: GCSStorageService;
  private workDir: string;
  private progressCallback?: (status: string, step: string, progress: number) => void;

  // Constants
  private readonly MAX_VIDEO_DURATION = 45; // seconds
  private readonly SEGMENT_DURATION = 5; // seconds per scene
  private readonly MAX_SCENES = 9; // Max 9 scenes = ~45 seconds

  constructor(
    openai: OpenAIService,
    kieLipSync: KieLipSyncService,
    ffmpeg: FFmpegService,
    captions: CaptionsService,
    workDir: string = './output',
    elevenlabs?: ElevenLabsService
  ) {
    this.openai = openai;
    this.kieLipSync = kieLipSync;
    this.ffmpeg = ffmpeg;
    this.captions = captions;
    this.elevenlabs = elevenlabs;
    this.gcsStorage = new GCSStorageService();
    this.workDir = workDir;
  }

  /**
   * Main generation method - fully automatic
   *
   * @param niche - Content niche (e.g., 'ai-tech', 'fitness')
   * @param topic - Video topic
   * @param portraitPath - Path to portrait image (URL or local)
   * @param platforms - Target platforms
   * @param backgroundMood - Background style mood
   * @param duration - Target video duration in seconds
   * @param progressCallback - Optional progress callback
   * @param replaceVoice - Optional: Replace Grok voice with ElevenLabs
   * @param voiceId - Optional: ElevenLabs voice ID (uses default if not provided)
   */
  async generate(
    niche: string,
    topic: string,
    portraitPath: string,
    platforms: Platform[],
    backgroundMood: BackgroundMood,
    duration: number,
    progressCallback?: (status: string, step: string, progress: number) => void,
    replaceVoice: boolean = false,
    voiceId?: string
  ): Promise<VideoGenerationResult> {
    const jobId = uuidv4();
    const state: WorkflowState = {
      jobId,
      status: 'initializing',
      progress: 0,
      currentStep: 'Initializing Grok Lip Sync Auto workflow',
      startTime: new Date(),
    };

    this.progressCallback = progressCallback;

    try {
      console.log('');
      console.log('🎤 GROK LIP SYNC AUTO GENERATION');
      console.log('='.repeat(60));
      console.log(`📋 Job ID: ${jobId}`);
      console.log(`🎯 Niche: ${niche}`);
      console.log(`📝 Topic: ${topic}`);
      console.log(`🖼️  Portrait: ${portraitPath}`);
      console.log(`🎨 Background Mood: ${backgroundMood}`);
      console.log(`⏱️  Target Duration: ${duration}s`);
      console.log(`🎯 Platforms: ${platforms.join(', ')}`);
      console.log(`🔊 Voice: ${replaceVoice ? `ElevenLabs (${voiceId || 'default'})` : 'Grok Native'}`);
      console.log('');

      // Create job directories
      const jobDir = path.join(this.workDir, jobId);
      const videoDir = path.join(jobDir, 'videos');
      const audioDir = path.join(jobDir, 'audio');
      const imageDir = path.join(jobDir, 'images');
      const finalDir = path.join(jobDir, 'final');

      this.createDirectories([jobDir, videoDir, audioDir, imageDir, finalDir]);

      // ========================================
      // STEP 1: Generate Script with Scenes
      // ========================================
      state.status = 'generating_script';
      state.currentStep = 'Generating script with AI';
      state.progress = 5;
      this.logProgress(state);

      const targetDuration = Math.min(duration, this.MAX_VIDEO_DURATION);
      const sceneCount = Math.min(
        Math.ceil(targetDuration / this.SEGMENT_DURATION),
        this.MAX_SCENES
      );

      console.log(`📝 Generating ${sceneCount} scenes for ${targetDuration}s video...`);

      const scenes = await this.generateScenesWithAI(niche, topic, sceneCount, backgroundMood);

      console.log(`✓ Generated ${scenes.length} scenes`);
      scenes.forEach((s, i) => {
        console.log(`   Scene ${i + 1}: "${s.dialogue.substring(0, 40)}..."`);
      });
      console.log('');

      // ========================================
      // STEP 2: Generate Lip Sync Video Segments
      // ========================================
      state.status = 'generating_video';
      state.currentStep = 'Generating lip-sync video segments';
      state.progress = 20;
      this.logProgress(state);

      const videoSegments = await this.generateWithFrameChaining(
        scenes,
        portraitPath,
        videoDir,
        imageDir,
        backgroundMood
      );

      const successfulSegments = videoSegments.filter(seg => seg.status === 'completed');

      if (successfulSegments.length === 0) {
        throw new Error('No video segments were successfully generated');
      }

      console.log('');
      console.log(`✓ Generated ${successfulSegments.length}/${scenes.length} segments with lip-sync`);
      console.log('');

      // ========================================
      // STEP 3: Concatenate Segments
      // ========================================
      state.status = 'assembling';
      state.currentStep = 'Assembling video segments';
      state.progress = 70;
      this.logProgress(state);

      const segmentPaths = successfulSegments
        .sort((a, b) => a.segmentIndex - b.segmentIndex)
        .map(seg => seg.videoUrl);

      const assembledVideoPath = path.join(finalDir, 'assembled_with_audio.mp4');
      const assembledVideo = await this.ffmpeg.concatenateWithAudio(
        segmentPaths,
        assembledVideoPath,
        true // Apply smooth transitions
      );

      console.log(`✓ Video assembled: ${assembledVideo.duration.toFixed(2)}s`);
      console.log('');

      // ========================================
      // STEP 4: Optional Voice Replacement (Per-Segment Time-Matched)
      // ========================================
      let finalVideoPath = assembledVideoPath;

      if (replaceVoice && this.elevenlabs) {
        state.status = 'replacing_voice';
        state.currentStep = 'Replacing voice with ElevenLabs (time-matched)';
        state.progress = 75;
        this.logProgress(state);

        finalVideoPath = await this.replaceVoiceWithElevenLabs(
          assembledVideoPath,
          scenes,
          segmentPaths,
          audioDir,
          finalDir
        );

        console.log('✓ Voice replaced with ElevenLabs (time-matched per segment)');
        console.log('');
      }

      // ========================================
      // STEP 5: Add Captions
      // ========================================
      state.status = 'adding_captions';
      state.currentStep = 'Adding captions';
      state.progress = 85;
      this.logProgress(state);

      try {
        const audioForCaptions = path.join(audioDir, 'for_captions.mp3');
        await this.ffmpeg.extractAudio(finalVideoPath, audioForCaptions);

        const captionedVideoPath = path.join(finalDir, 'final_with_captions.mp4');
        await this.captions.addCaptionsWorkflow(
          finalVideoPath,
          audioForCaptions,
          captionedVideoPath,
          YOUTUBE_SHORTS_STYLE
        );

        finalVideoPath = captionedVideoPath;
        console.log('✓ Captions added');
        console.log('');
      } catch (error) {
        console.warn(`⚠️  Caption generation failed, continuing without: ${error}`);
      }

      // ========================================
      // COMPLETED!
      // ========================================
      state.status = 'completed';
      state.currentStep = 'Generation complete';
      state.progress = 100;
      state.endTime = new Date();
      this.logProgress(state);

      const finalDuration = await this.ffmpeg.getDuration(finalVideoPath);
      const processingTime = (state.endTime.getTime() - state.startTime.getTime()) / 1000;

      console.log('');
      console.log('='.repeat(60));
      console.log('✅ GROK LIP SYNC AUTO GENERATION COMPLETE!');
      console.log('='.repeat(60));
      console.log(`⏱️  Processing time: ${processingTime.toFixed(2)}s`);
      console.log(`📁 Output: ${finalVideoPath}`);
      console.log(`🎬 Duration: ${finalDuration.toFixed(2)}s`);
      console.log(`🎯 Scenes: ${scenes.length}`);
      console.log(`🔊 Audio: ${replaceVoice ? 'ElevenLabs (time-matched)' : 'Grok Native Lip Sync'}`);
      console.log('');

      return {
        success: true,
        videoPath: finalVideoPath,
        duration: finalDuration,
        segments: successfulSegments.length,
      };
    } catch (error) {
      state.status = 'failed';
      state.error = String(error);
      state.endTime = new Date();

      console.error('');
      console.error('❌ GROK LIP SYNC AUTO GENERATION FAILED');
      console.error(`Error: ${error}`);
      console.error('');

      return {
        success: false,
        error: String(error),
      };
    }
  }

  /**
   * Generate scenes using OpenAI
   * Each scene has dialogue (what to say) and visual (background description)
   */
  private async generateScenesWithAI(
    niche: string,
    topic: string,
    sceneCount: number,
    backgroundMood: BackgroundMood
  ): Promise<GeneratedScene[]> {
    const moodDescriptions: Record<BackgroundMood, string> = {
      dramatic: 'dramatic, cinematic backgrounds with volumetric lighting, god rays, and epic shadows',
      futuristic: 'futuristic, cyberpunk backgrounds with holograms, neon lights, and tech aesthetics',
      nature: 'beautiful nature backgrounds with golden hour lighting, mist, and photorealistic landscapes',
      urban: 'urban night scenes with rain-slicked streets, neon reflections, and moody atmosphere',
      corporate: 'professional, corporate settings with sleek glass surfaces and soft bokeh lighting',
      custom: 'appropriate backgrounds matching the content',
    };

    const prompt = `Generate a ${sceneCount}-scene video script for the topic: "${topic}" in the ${niche} niche.

Each scene should have:
1. DIALOGUE: What the character says (2-3 sentences, conversational, engaging)
2. VISUAL: Background description (${moodDescriptions[backgroundMood]})

Format your response as JSON array:
[
  {
    "id": "1",
    "title": "Scene Title",
    "dialogue": "What the character says...",
    "visual": "Description of the background environment..."
  },
  ...
]

Requirements:
- Each scene's dialogue should be 15-25 words (fits in ~5 seconds when spoken)
- Visuals should be vivid, cinematic, and spectacular
- Content should be engaging and hook the viewer
- Keep the flow natural between scenes
- NO introductions like "Hey everyone" - start with value immediately

Return ONLY the JSON array, no other text.`;

    try {
      const response = await this.openai.generateRaw(prompt, 2000);

      // Parse JSON from response
      const jsonMatch = response.match(/\[[\s\S]*\]/);
      if (!jsonMatch) {
        throw new Error('Failed to parse scenes JSON from AI response');
      }

      const scenes: GeneratedScene[] = JSON.parse(jsonMatch[0]);

      // Validate and clean scenes
      return scenes.slice(0, sceneCount).map((scene, index) => ({
        id: scene.id || String(index + 1),
        title: scene.title || `Scene ${index + 1}`,
        dialogue: scene.dialogue.trim(),
        visual: scene.visual.trim(),
      }));
    } catch (error) {
      console.error('Failed to generate scenes with AI:', error);
      throw new Error(`Script generation failed: ${error}`);
    }
  }

  /**
   * Generate lip-sync segments with frame chaining
   * Copied from grok-lipsync.workflow.ts
   */
  private async generateWithFrameChaining(
    scenes: GeneratedScene[],
    initialPortraitPath: string,
    videoDir: string,
    imageDir: string,
    mood: BackgroundMood
  ): Promise<{ videoUrl: string; segmentIndex: number; status: 'completed' | 'failed' }[]> {
    const results: { videoUrl: string; segmentIndex: number; status: 'completed' | 'failed' }[] = [];
    let currentSeedPath = initialPortraitPath;

    console.log('');
    console.log('🔗 FRAME CHAINING ENABLED');
    console.log(`   Initial seed: ${initialPortraitPath}`);
    console.log('');

    for (let i = 0; i < scenes.length; i++) {
      const scene = scenes[i];
      const isFirstSegment = i === 0;
      const isLastSegment = i === scenes.length - 1;

      console.log(`\n${'='.repeat(60)}`);
      console.log(`🎤 SEGMENT ${i + 1}/${scenes.length}: ${scene.title}`);
      console.log(`${'='.repeat(60)}`);
      console.log(`   Dialogue: "${scene.dialogue.substring(0, 50)}${scene.dialogue.length > 50 ? '...' : ''}"`);

      // Generate lip-sync video segment
      const result = await this.kieLipSync.generateWithLipSync(
        currentSeedPath,
        scene.dialogue,
        scene.visual,
        videoDir,
        i,
        mood,
        !isFirstSegment
      );

      results.push({
        videoUrl: result.videoUrl,
        segmentIndex: i,
        status: result.status,
      });

      if (result.status !== 'completed') {
        console.error(`   ❌ Segment ${i + 1} failed`);
        continue;
      }

      console.log(`   ✓ Segment ${i + 1} generated with lip-sync audio`);

      // Frame chaining for next segment
      if (!isLastSegment) {
        try {
          const compositedFramePath = path.join(imageDir, `transition_composite_${i}.jpg`);

          console.log(`   🔄 FRAME CHAINING STEP 1: Extracting last frame and compositing...`);
          console.log(`      Video URL: ${result.videoUrl}`);
          console.log(`      Portrait: ${initialPortraitPath}`);
          console.log(`      Output: ${compositedFramePath}`);

          await this.ffmpeg.extractLastFrameAndComposite(
            result.videoUrl,
            initialPortraitPath,
            compositedFramePath
          );

          if (!fs.existsSync(compositedFramePath)) {
            throw new Error(`Composited frame file not created at ${compositedFramePath}`);
          }

          const frameStats = fs.statSync(compositedFramePath);
          console.log(`   ✓ Composited frame created (${(frameStats.size / 1024).toFixed(1)}KB)`);

          if (frameStats.size < 1000) {
            console.warn(`   ⚠️  Warning: Composited frame is very small (${frameStats.size} bytes) - may be blank`);
          }

          console.log(`   🔄 FRAME CHAINING STEP 2: Uploading to GCS...`);
          const timestamp = Date.now();
          const remoteFileName = `lipsync_auto_composite_${timestamp}_segment_${i}.jpg`;
          const gcsUrl = await this.gcsStorage.uploadImage(compositedFramePath, remoteFileName);
          console.log(`   ✓ Uploaded to GCS: ${gcsUrl}`);

          console.log(`   🔄 FRAME CHAINING STEP 3: Waiting for GCS propagation...`);
          await new Promise(resolve => setTimeout(resolve, 4000));

          currentSeedPath = gcsUrl;
          console.log(`   ✅ Frame chain READY for segment ${i + 2}: ${gcsUrl.substring(0, 80)}...`);
        } catch (error: any) {
          console.error(`   ❌ FRAME CHAINING FAILED`);
          console.error(`      Error: ${error.message}`);
          console.error(`      Stack: ${error.stack}`);
          console.warn(`   ⚠️  Falling back to initial portrait for segment ${i + 2}`);
          currentSeedPath = initialPortraitPath;
        }
      }
    }

    return results;
  }

  /**
   * Create directories
   */
  private createDirectories(dirs: string[]): void {
    dirs.forEach(dir => {
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }
    });
  }

  /**
   * Log progress
   */
  private logProgress(state: WorkflowState): void {
    const progressBar = this.createProgressBar(state.progress);
    console.log(`[${progressBar}] ${state.progress}% - ${state.currentStep}`);

    if (this.progressCallback) {
      this.progressCallback(state.status, state.currentStep, state.progress);
    }
  }

  /**
   * Create ASCII progress bar
   */
  private createProgressBar(progress: number, width: number = 30): string {
    const filled = Math.floor((progress / 100) * width);
    const empty = width - filled;
    return '█'.repeat(filled) + '░'.repeat(empty);
  }

  /**
   * Replace Grok's native voice with ElevenLabs (Speech-to-Speech)
   *
   * This uses Speech-to-Speech API for accurate timing:
   * 1. Extract audio from each video segment (Grok's voice)
   * 2. Convert to target voice using Speech-to-Speech (preserves timing!)
   * 3. Replace audio in each segment (no stretching needed)
   * 4. Concatenate all voice-replaced segments
   *
   * Speech-to-Speech is better than TTS + time-stretch because:
   * - Preserves natural speech pacing from Grok
   * - No artificial speed-up/slow-down artifacts
   * - Better lip-sync accuracy
   */
  private async replaceVoiceWithElevenLabs(
    assembledVideoPath: string,
    scenes: GeneratedScene[],
    videoSegmentPaths: string[],
    audioDir: string,
    finalDir: string
  ): Promise<string> {
    if (!this.elevenlabs) {
      console.warn('   ⚠️  ElevenLabs not configured, skipping voice replacement');
      return assembledVideoPath;
    }

    console.log('');
    console.log('🎤 VOICE REPLACEMENT (Speech-to-Speech)');
    console.log('   Converting Grok voice to ElevenLabs using Speech-to-Speech...');
    console.log(`   Processing ${videoSegmentPaths.length} segments...`);
    console.log('   (Speech-to-Speech preserves original timing - no stretching!)');
    console.log('');

    const voiceReplacedSegments: string[] = [];

    for (let i = 0; i < videoSegmentPaths.length; i++) {
      const segmentPath = videoSegmentPaths[i];
      const scene = scenes[i];

      console.log(`   📹 Segment ${i + 1}/${videoSegmentPaths.length}${scene ? `: "${scene.dialogue.substring(0, 40)}..."` : ''}`);

      try {
        // Step 1: Get original video duration for comparison
        const videoDuration = await this.ffmpeg.getDuration(segmentPath);
        console.log(`      Original duration: ${videoDuration.toFixed(2)}s`);

        // Step 2: Use Speech-to-Speech to convert Grok's voice to target voice
        // This extracts audio, converts it, and returns the path
        const { audioPath: convertedAudioPath, duration: convertedDuration } =
          await this.elevenlabs.convertVideoAudioToVoice(
            segmentPath,
            audioDir,
            i
          );

        console.log(`      Converted duration: ${convertedDuration.toFixed(2)}s (should match original)`);

        // Step 3: Replace audio in video (no stretching needed - timing is preserved!)
        const voiceReplacedPath = path.join(audioDir, `segment_${i}_voice_replaced.mp4`);
        await this.ffmpeg.replaceAudioTrack(
          segmentPath,
          convertedAudioPath,
          voiceReplacedPath
        );

        voiceReplacedSegments.push(voiceReplacedPath);
        console.log(`      ✓ Segment ${i + 1} voice converted via Speech-to-Speech`);
        console.log('');

        // Cleanup converted audio file
        if (fs.existsSync(convertedAudioPath)) {
          fs.unlinkSync(convertedAudioPath);
        }

      } catch (error) {
        console.error(`      ❌ Failed to convert voice in segment ${i + 1}: ${error}`);
        // Fall back to original segment if voice replacement fails
        voiceReplacedSegments.push(segmentPath);
      }
    }

    // Step 4: Concatenate all voice-replaced segments
    console.log('   🔗 Concatenating voice-replaced segments...');
    const finalVoiceReplacedPath = path.join(finalDir, 'with_elevenlabs_voice.mp4');

    const assembled = await this.ffmpeg.concatenateWithAudio(
      voiceReplacedSegments,
      finalVoiceReplacedPath,
      true // Apply smooth transitions
    );

    console.log('');
    console.log('   ✓ Voice replacement complete (Speech-to-Speech)');
    console.log(`   Final duration: ${assembled.duration.toFixed(2)}s`);

    return finalVoiceReplacedPath;
  }
}
